/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
torch version ::: 1.9.0+cu111
device        ::: cuda:0
Dataset
DataLoader
Model
loss
opt
tr_loss_avg ::: 1.8822507858276367, tr_acc_avg ::: 0.5708333333333334
val_loss_avg ::: 1.517099380493164, val_acc_avg ::: 0.77490234375
tr_loss_avg ::: 1.30740487575531, tr_acc_avg ::: 0.7929188829787234
val_loss_avg ::: 1.1024678945541382, val_acc_avg ::: 0.82177734375
tr_loss_avg ::: 1.0054823160171509, tr_acc_avg ::: 0.8215979609929078
val_loss_avg ::: 0.883467972278595, val_acc_avg ::: 0.8396484375
tr_loss_avg ::: 0.8323227167129517, tr_acc_avg ::: 0.838209219858156
val_loss_avg ::: 0.7475793361663818, val_acc_avg ::: 0.854296875
tr_loss_avg ::: 0.7224610447883606, tr_acc_avg ::: 0.8502050088652483
val_loss_avg ::: 0.6602417826652527, val_acc_avg ::: 0.86455078125
tr_loss_avg ::: 0.6465295553207397, tr_acc_avg ::: 0.8605441046099291
val_loss_avg ::: 0.5991069674491882, val_acc_avg ::: 0.87158203125
tr_loss_avg ::: 0.5911681652069092, tr_acc_avg ::: 0.8671043882978723
val_loss_avg ::: 0.5495259165763855, val_acc_avg ::: 0.8779296875
tr_loss_avg ::: 0.5485195517539978, tr_acc_avg ::: 0.8735150709219858
val_loss_avg ::: 0.5115019679069519, val_acc_avg ::: 0.88173828125
tr_loss_avg ::: 0.5154215097427368, tr_acc_avg ::: 0.8779532358156028
val_loss_avg ::: 0.4873875677585602, val_acc_avg ::: 0.8873046875
tr_loss_avg ::: 0.4883185923099518, tr_acc_avg ::: 0.8818317819148936
Traceback (most recent call last):
  File "simple_training.py", line 129, in <module>
    wandb.log({"plot": fig})
NameError: name 'fig' is not defined
val_loss_avg ::: 0.4593706727027893, val_acc_avg ::: 0.89091796875
training finishes